version: "2.4"

networks:
  provenance-net:
    driver: bridge
  traefik_web:
    external:
      name: traefik_web

services:
  provenance-flask:
    mem_limit: 1G
    mem_reservation: 1G
    cpus: 4
    build:
      context: '../'
      dockerfile: docker/provenance-Dockerfile
    ports:
      - 12002:5000
    networks:
      - provenance-net
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=12002"
      - "traefik.http.routers.provenance.rule=Host(`provenance.devserver.pharmb.io`)"
      - "traefik.http.routers.provenance.tls.certresolver=myresolver"
      - "traefik.http.routers.provenance.entrypoints=websecure"
